baseURL = "https://ZiggorX.github.io/"
languageCode = "en-gb"
theme = "anatole"

[params]

title = "Cyber Security blog: By Ziggor"
author = "AEC"
description = "Vmricdb sw se gzqd, azozc fm mgxzp addkrcgjdvz."
profilePicture = "images/profilepic.jpg"
mainSections = ["Blog"]
